<?php

 define('REQUEST_IBLOCK', 1);
 define('REQUEST_SPECIFICATION_IBLOCK', 3);
 define('REQUEST_SUPPLIER_IBLOCK', 4);
 define('REQUEST_SUPPLIER_CONTACT_IBLOCK', 2);

 define('REQUEST_IS_BLOCKED_ID', 1);
 define('REQUEST_SPECIFICATION_IS_REPLACEMENT', 2);

// define('REQUEST_TOKEN', '2feoiiqokh5cpppl');
 define('REQUEST_TOKEN', 'ts3m91kue8ons69x');