<?php

 define('REQUEST_IBLOCK', 7);
 define('REQUEST_SPECIFICATION_IBLOCK', 8);
 define('REQUEST_SUPPLIER_IBLOCK', 10);
 define('REQUEST_SUPPLIER_CONTACT_IBLOCK', 9);

 define('REQUEST_IS_BLOCKED_ID', 2);
 define('REQUEST_SPECIFICATION_IS_REPLACEMENT', 1);

 define('REQUEST_TOKEN', '2feoiiqokh5cpppl');